name: Continuous integration

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js 12.13.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.x'
      - name: Cache yarn directory
        id: cache-yarn-dir
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.cache-yarn-dir.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn run lint
      - name: Run tests
        run: yarn run test
      - name: Build
        run: yarn run build
